# Generated by Django 2.2.1 on 2019-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twice',
            name='position',
            field=models.CharField(max_length=20),
        ),
    ]
