# Generated by Django 2.2.1 on 2019-05-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0002_auto_20190525_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twice',
            name='position',
            field=models.TextField(max_length=20),
        ),
    ]
